POST http://localhost:3001/api/memos
Content-Type: application/json

{
    "title": "Third Memo",
    "content": "Write more articles on nuance"
}

###

GET http://localhost:3001/api/memos
Content-Type: application/json

###

PUT  http://localhost:3001/api/memos/629afbaa7d23f593beb7ff46
Content-Type: application/json

{
    "title": "Hello",
    "content": "World"
}

###

DELETE  http://localhost:3001/api/memos/629b04447d23f593beb7ff75
Content-Type: application/json
