POST http://localhost:3001/api/memos
Content-Type: application/json

{
    "content": "This is the fourth memo"
}

###

GET http://localhost:3001/api/memos
Content-Type: application/json

###

PUT  http://localhost:3001/api/memos/62995c2115dc234ed406a70b
Content-Type: application/json

{
    "content": "hello world"
}

###

DELETE  http://localhost:3001/api/memos/629961acafb8b4d914fb6da5
Content-Type: application/json
